# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
#Settings for the first centOS machine
  config.vm.define "centos-vm1" do |vm1|
    vm1.vm.hostname = "centos-vm1"
    vm1.vm.box = "bento/centos-7"
    vm1.vm.network "private_network", ip: "192.168.10.2"

  
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "centos-vm1"
      vb.gui = false
      vb.memory = 2048
    end
  end 

#Settings for the second centOS machine
  config.vm.define "centos-vm2" do |vm2|
    vm2.vm.hostname = "centos-vm2"
    vm2.vm.box = "bento/centos-7"
    vm2.vm.network "private_network", ip: "192.168.10.3"

  
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "centos-vm2"
      vb.gui = false
      vb.memory = 2048
    end
  end
  
#Vagrant will create his inventory file to store ansible config
#The path of the inventory file will be in ./.vagrant/provisioner/ansible/inventory/vagrant_ansible_inventory  
	
end
