---
# handlers file for anto.docker_centos

#This handler is triggered when the space is not enough and it increases the space amount
    - name: Upgrade space
      parted:
        device: /dev/sda
        number: 1
        state: present
        part_end: 40GiB
        
#Now the second handler can install docker
    - name: Install docker now    
      dnf:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
